version: '3.8'

services:
  mongo:
    image: mongo:8
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    restart: always
    ports:
      - "27017:27017"  # Expose MongoDB on the default port

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    depends_on:
      - mongo
    env_file:
      - .env  # Load environment variables from .env
    ports:
      - "3000:3000"  # Expose the NestJS app on port 3000
    volumes:
      - .:/app  # Mount the current directory for live reload in dev mode
      - /app/node_modules  # Prevents overwriting node_modules in the container
    command: ["yarn", "start:dev"]  # Start in development mode
    restart: always

volumes:
  mongo_data:
